### ISSUE TITLE
timestamp of your dataset

### ISSUE THREAD

**Issue by thisparticle** [KIT-ISAS/lili-om#52]
hello, it seems like the timestamp of livox lidar in rosbag is different from the ground-truth(aka. GNSS) timestamp,  and when I use them to evaluate estimated trajectories, evo shows error, do you get through this problem?

**Comment by kailaili** [comment]
Hi, we do not use GNSS as the ground truth as it is not accurate over the whole trajectory due to well-known issues such as signal occlusion, multipath effect, etc. In the paper, end-to-end errors are used for quantifying drift. Nevertheless, having different time stamps is fine for aligning trajectories in evaluation.
